version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
        POSTGRES_USER: ${POSTGRES_USER:-postgres}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
        PGDATA: /data/postgres
    volumes:
        - postgres-data:/data/postgres
    ports:
        - "5432:5432"

volumes:
    postgres-data: